import Image from "next/image";
import Footer from "./component/footer";
import Navbar from "./component/navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />

        <Image
          src={"/assests/pictures/mesh-895.png"}
          width={1500}
          height={1300}
          alt="bg-cover"
          className="fixed h-full"
        />

        {children}
        <Footer />
      </body>
    </html>
  );
}
